plugins:
  - rubocop-rails

AllCops:
 NewCops: enable
 SuggestExtensions: false
 TargetRubyVersion: 2.6
 Exclude:
   - 'bin/**/*'
   - 'vendor/**/*'
   - 'db/**/*'
   - 'config/**/*'
   - 'script/**/*'
   - 'spec/rails_helper.rb'
   - 'Rakefile'

Documentation:
 Enabled: false

Style/FrozenStringLiteralComment:
 Enabled: false
